/*
 * Firefox Guardian API
 *
 * API to manage Guardian accounts, devices and servers
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// AccountDetailsSubscriptionsVpn - The VPN Subscription information
type AccountDetailsSubscriptionsVpn struct {

	// Is the VPN subscription active?
	Active bool `json:"active"`

	CreatedAt string `json:"created_at,omitempty"`

	RenewsOn string `json:"renews_on,omitempty"`
}
