/*
 * Firefox Guardian API
 *
 * API to manage Guardian accounts, devices and servers
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ErrorSchema struct {

	// The HTTP status code.
	Code int32 `json:"code,omitempty"`

	// The error number.
	Errno int32 `json:"errno,omitempty"`

	// The error message.
	Error string `json:"error,omitempty"`
}
