/*
 * Firefox Guardian API
 *
 * API to manage Guardian accounts, devices and servers
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type VerifyTokenResponse struct {
	User AccountDetails `json:"user,omitempty"`

	// API authentication token
	Token string `json:"token,omitempty"`
}
