/*
 * Firefox Guardian API
 *
 * API to manage Guardian accounts, devices and servers
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type AccountDetails struct {
	Email string `json:"email,omitempty"`

	// User defined display name. Empty string for users that haven't set one.
	DisplayName string `json:"display_name,omitempty"`

	Avatar string `json:"avatar,omitempty"`

	Subscriptions AccountDetailsSubscriptions `json:"subscriptions,omitempty"`

	// List of devices
	Devices []GuardianDevice `json:"devices,omitempty"`

	MaxDevices int `json:"max_devices,omitempty"`
}
