/*
 * Firefox Guardian API
 *
 * API to manage Guardian accounts, devices and servers
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type LoginResponse struct {

	// URL to open in the user's browser
	LoginUrl string `json:"login_url,omitempty"`

	// URL to poll for authentication status
	VerificationUrl string `json:"verification_url,omitempty"`

	// The expiration date for the URLs
	ExpiresOn string `json:"expires_on,omitempty"`

	// Poll interval in seconds
	PollInterval float32 `json:"poll_interval,omitempty"`
}
