/*
 * Firefox Guardian API
 *
 * API to manage Guardian accounts, devices and servers
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type BalrogVersionResponse struct {

	// The version string
	Version string `json:"version,omitempty"`

	// The url string
	URL string `json:"url,omitempty"`

	// The required bool
	Required bool `json:"required"`

	// The hashFunction string
	HashFunction string `json:"hashFunction,omitempty"`

	// The hashValue string
	HashValue string `json:"hashValue,omitempty"`

	// (optional) release message
	Message string `json:"message,omitempty"`
}
