/*
 * Firefox Guardian API
 *
 * API to manage Guardian accounts, devices and servers
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type WindowsResponse struct {

	// Latest version of the client.
	Latest VersionResponse `json:"latest,omitempty"`

	Minimum VersionResponse `json:"minimum,omitempty"`
}
