/*
 * Firefox Guardian API
 *
 * API to manage Guardian accounts, devices and servers
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type VPNVersionResponse struct {
	Windows WindowsResponse `json:"windows,omitempty"`
}
