/*
 * Firefox Guardian API
 *
 * API to manage Guardian accounts, devices and servers
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type BalrogRootSignature struct {

	// The Signature string
	Signature string `json:"signature,omitempty"`
}
