/*
 * Firefox Guardian API
 *
 * API to manage Guardian accounts, devices and servers
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type VersionResponse struct {

	// The version string
	Version string `json:"version,omitempty"`

	// The release date
	ReleasedOn string `json:"released_on,omitempty"`

	// (optional) release message
	Message string `json:"message,omitempty"`
}
