/*
 * Firefox Guardian API
 *
 * API to manage Guardian accounts, devices and servers
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// AccountDetailsSubscriptions - Subscriptions information
type AccountDetailsSubscriptions struct {
	Vpn AccountDetailsSubscriptionsVpn `json:"vpn,omitempty"`
}
